{
  "events": [
    {
      "eventID": 798248,
      "eventDateID": 14298,
      "EventDate": "2015-04-10T00:00:00",
      "StartTime": "7:30 PM",
      "EndTime": "8:30 PM",
      "Title": "Faculty Series: Doug Black, euphonium",
      "Description": "Faculty performance also featuring special guest Stephanie Landry, euphonium.",
      "PriceDescription": "N/A",
      "IsGLI": false,
      "Location": "Barnes Recital Hall",
      "Building": "Barnes Recital Hall",
      "ContactPersonName": "Donna Guerra",
      "ContactPersonPhoneNumber": "323-2255"
    },
    {
      "eventID": 797419,
      "eventDateID": 12711,
      "EventDate": "2015-04-10T00:00:00",
      "StartTime": "8:00 PM",
      "EndTime": "11:00 PM",
      "Title": "Leading Ladies",
      "Description": "A madcap romp of disguise, fortune hunting, small town life and romance, Ken Ludwig's LEADING LADIES chronicles two down-on-their luck Shakespearian Actors, Jack and Leo, who hatch a plot to pass themselves off as two English women to scam an elderly woman of her fortune. Disastrous decisions lead to romantic entanglements, naughty innuendos, mistaken identities and hilarious comedy. Think Some Like it Hot meets Charlie's Aunt\r\n\r\n",
      "PriceDescription": "$8 w/ WU ID, $15 w/o",
      "IsGLI": false,
      "Location": "Johnson Theatre J106",
      "Building": "Johnson",
      "ContactPersonName": "Ramona Kundl",
      "ContactPersonPhoneNumber": "323-2287"
    },
    {
      "eventID": 797419,
      "eventDateID": 12712,
      "EventDate": "2015-04-11T00:00:00",
      "StartTime": "8:00 PM",
      "EndTime": "11:00 PM",
      "Title": "Leading Ladies",
      "Description": "A madcap romp of disguise, fortune hunting, small town life and romance, Ken Ludwig's LEADING LADIES chronicles two down-on-their luck Shakespearian Actors, Jack and Leo, who hatch a plot to pass themselves off as two English women to scam an elderly woman of her fortune. Disastrous decisions lead to romantic entanglements, naughty innuendos, mistaken identities and hilarious comedy. Think Some Like it Hot meets Charlie's Aunt\r\n\r\n",
      "PriceDescription": "$8 w/ WU ID, $15 w/o",
      "IsGLI": false,
      "Location": "Johnson Theatre J106",
      "Building": "Johnson",
      "ContactPersonName": "Ramona Kundl",
      "ContactPersonPhoneNumber": "323-2287"
    },
    {
      "eventID": 797445,
      "eventDateID": 12904,
      "EventDate": "2015-04-12T00:00:00",
      "StartTime": "2:00 PM",
      "EndTime": "5:00 PM",
      "Title": "Leading Ladies",
      "Description": "A madcap romp of disguise, fortune hunting, small town life and romance, Ken Ludwig's LEADING LADIES chronicles two down-on-their luck Shakespearian Actors, Jack and Leo, who hatch a plot to pass themselves off as two English women to scam an elderly woman of her fortune. Disastrous decisions lead to romantic entanglements, naughty innuendos, mistaken identities and hilarious comedy. Think Some Like it Hot meets Charlie's Aunt\r\n\r\n",
      "PriceDescription": "$8 w/ WU ID, $15 w/o",
      "IsGLI": false,
      "Location": "Johnson Theatre J106",
      "Building": "Johnson",
      "ContactPersonName": "Ramona Kundl",
      "ContactPersonPhoneNumber": "323-2287"
    },
    {
      "eventID": 797942,
      "eventDateID": 13868,
      "EventDate": "2015-04-12T00:00:00",
      "StartTime": "4:00 PM",
      "EndTime": "5:00 PM",
      "Title": "Ensemble Series: Winthrop Brass Ensemble",
      "Description": "Student ensemble performance",
      "PriceDescription": "N/A",
      "IsGLI": false,
      "Location": "Barnes Recital Hall",
      "Building": "Barnes Recital Hall",
      "ContactPersonName": "Donna Guerra",
      "ContactPersonPhoneNumber": "323-2255"
    },
    {
      "eventID": 798262,
      "eventDateID": 14316,
      "EventDate": "2015-04-12T00:00:00",
      "StartTime": "7:00 PM",
      "EndTime": "9:00 PM",
      "Title": "ICE at Winthrop: Christine Dakin and Jane Wang",
      "Description": "ICE at Winthrop welcomes Christine Dakin and Jane Wang's presentation, \"How Art and Science Intersect.\" Christine Dakin is the former co-Artistic Director of the Martha Graham Dance Company. Jane Wang is a theoretical physicist studying the physics of living organisms. She received her PhD in Physics from University of Chicago in 1996. She joined Cornell in 1999, where she is now a professor of mechanical and aerospace engineering and physics.",
      "PriceDescription": "N/A",
      "IsGLI": false,
      "Location": "Dina's Place",
      "Building": "DiGiorgio Campus Center",
      "ContactPersonName": "Amanda Woolwine",
      "ContactPersonPhoneNumber": "323-2399"
    },
    {
      "eventID": 798255,
      "eventDateID": 14309,
      "EventDate": "2015-04-12T00:00:00",
      "StartTime": "8:00 PM",
      "EndTime": "9:30 PM",
      "Title": "ICE at Winthrop: Christine Dakin and Jane Wang Reception",
      "Description": "Reception for Winthrop's ICE Initiative speakers Christine Dakin and Jane Wang.",
      "PriceDescription": "N/A",
      "IsGLI": false,
      "Location": "Main Lobby",
      "Building": "DiGiorgio Campus Center",
      "ContactPersonName": "Amanda Woolwine",
      "ContactPersonPhoneNumber": "323-2399"
    },
    {
      "eventID": 797436,
      "eventDateID": 12894,
      "EventDate": "2015-04-14T00:00:00",
      "StartTime": "7:30 PM",
      "EndTime": "8:30 PM",
      "Title": "Ensemble Series: Winthrop Clarinet Choir",
      "Description": "student ensemble performance",
      "PriceDescription": "N/A",
      "IsGLI": false,
      "Location": "Barnes Recital Hall",
      "Building": "Barnes Recital Hall",
      "ContactPersonName": "Donna Guerra",
      "ContactPersonPhoneNumber": "323-2255"
    },
    {
      "eventID": 798259,
      "eventDateID": 14313,
      "EventDate": "2015-04-14T00:00:00",
      "StartTime": "8:00 PM",
      "EndTime": "9:30 PM",
      "Title": "Forum, \"What is Socialism?\"",
      "Description": "Professors Smith & Disney will make presentations after which two students will comment  on the presentations.   After the students' presentations, the floor will be opened to questions from the audience. Each professor's presentation will be 20 minutes, each student's presentation will be 10 minutes, and the Q&A session will last 30 minutes.",
      "PriceDescription": "N/A",
      "IsGLI": true,
      "Location": "G02",
      "Building": "Owens Hall",
      "ContactPersonName": "Professor Stephen Smith",
      "ContactPersonPhoneNumber": "323-4661"
    },
    {
      "eventID": 797437,
      "eventDateID": 12895,
      "EventDate": "2015-04-15T00:00:00",
      "StartTime": "7:30 PM",
      "EndTime": "8:30 PM",
      "Title": "Ensemble Series: Winthrop Symphony Orchestra",
      "Description": "student ensemble performance",
      "PriceDescription": "N/A",
      "IsGLI": false,
      "Location": "Byrnes Auditorium",
      "Building": "Byrnes Auditorium",
      "ContactPersonName": "Donna Guerra",
      "ContactPersonPhoneNumber": "323-2255"
    },
    {
      "eventID": 798367,
      "eventDateID": 14443,
      "EventDate": "2015-04-16T00:00:00",
      "StartTime": "5:30 PM",
      "EndTime": "6:30 PM",
      "Title": "Ensemble Series: Winthrop University Opera Workshop",
      "Description": "Opera Workshop students will perform Mozart Scenes from operas: Die Zauberflöte, Le nozze di Figaro, and Così fan tutte",
      "PriceDescription": "N/A",
      "IsGLI": false,
      "Location": "Barnes Recital Hall",
      "Building": "Barnes Recital Hall",
      "ContactPersonName": "Donna Guerra",
      "ContactPersonPhoneNumber": "323-2255"
    },
    {
      "eventID": 797438,
      "eventDateID": 13933,
      "EventDate": "2015-04-16T00:00:00",
      "StartTime": "7:30 PM",
      "EndTime": "8:30 PM",
      "Title": "Ensemble Series: Winthrop Jazz Ensemble",
      "Description": "student ensemble performance",
      "PriceDescription": "N/A",
      "IsGLI": false,
      "Location": "Byrnes Auditorium",

      "Building": "Barnes Recital Hall",
      "ContactPersonName": "Donna Guerra",
      "ContactPersonPhoneNumber": "323-2255"
    },
    {
      "eventID": 797420,
      "eventDateID": 12713,
      "EventDate": "2015-04-18T00:00:00",
      "StartTime": "2:00 PM",
      "EndTime": "4:00 PM",
      "Title": "Spring One-Act Festival",
      "Description": "A lively and entertaining mixture of one-act plays directed by advanced theatre students. Adult content. Adult language. \r\n\r\n",
      "PriceDescription": "$8 w/ WU ID, $15 w/o",
      "IsGLI": false,
      "Location": "Johnson Studio Theatre J117",
      "Building": "Johnson",
      "ContactPersonName": "Ramona Kundl",
      "ContactPersonPhoneNumber": "323-2287"
    },
    {
      "eventID": 797420,
      "eventDateID": 12714,
      "EventDate": "2015-04-19T00:00:00",
      "StartTime": "2:00 PM",
      "EndTime": "4:00 PM",
      "Title": "Spring One-Act Festival",
      "Description": "A lively and entertaining mixture of one-act plays directed by advanced theatre students. Adult content. Adult language. \r\n\r\n",
      "PriceDescription": "$8 w/ WU ID, $15 w/o",
      "IsGLI": false,
      "Location": "Johnson Studio Theatre J117",
      "Building": "Johnson",
      "ContactPersonName": "Ramona Kundl",
      "ContactPersonPhoneNumber": "323-2287"
    },
    {
      "eventID": 797076,
      "eventDateID": 11851,
      "EventDate": "2015-04-19T00:00:00",
      "StartTime": "2:00 PM",
      "EndTime": "5:00 PM",
      "Title": "Student Choreography Showcase",
      "Description": "Enjoy a night of works choreographed by senior dance students.",
      "PriceDescription": "$5 w/ WU ID, $10 w/o",
      "IsGLI": false,
      "Location": "106/Johnson Theatre",
      "Building": "Johnson",
      "ContactPersonName": "Ramona Kundl",
      "ContactPersonPhoneNumber": "323-2287"
    },
    {
      "eventID": 797440,
      "eventDateID": 12898,
      "EventDate": "2015-04-20T00:00:00",
      "StartTime": "7:30 PM",
      "EndTime": "8:30 PM",
      "Title": "Ensemble Series: Winthrop Collegiate Choir/Winthrop Jazz Voices",
      "Description": "student ensemble performance",
      "PriceDescription": "N/A",
      "IsGLI": false,
      "Location": "Barnes Recital Hall",
      "Building": "Barnes Recital Hall",
      "ContactPersonName": "Donna Guerra",
      "ContactPersonPhoneNumber": "323-2255"
    },
    {
      "eventID": 797439,
      "eventDateID": 12897,
      "EventDate": "2015-04-21T00:00:00",
      "StartTime": "7:30 PM",
      "EndTime": "8:30 PM",
      "Title": "Ensemble Series: Winthrop Chorale/Winthrop Chamber Singers",
      "Description": "student ensemble performance",
      "PriceDescription": "N/A",
      "IsGLI": false,
      "Location": "Byrnes Auditorium",
      "Building": "Byrnes Auditorium",
      "ContactPersonName": "Donna Guerra",
      "ContactPersonPhoneNumber": "323-2255"
    },
    {
      "eventID": 797441,
      "eventDateID": 12899,
      "EventDate": "2015-04-22T00:00:00",
      "StartTime": "7:30 PM",
      "EndTime": "8:30 PM",
      "Title": "Ensemble Series: Winthrop Chamber Orchestra",
      "Description": "student ensemble performance",
      "PriceDescription": "N/A",
      "IsGLI": false,
      "Location": "Barnes Recital Hall",
      "Building": "Barnes Recital Hall",
      "ContactPersonName": "Donna Guerra",
      "ContactPersonPhoneNumber": "323-2255"
    },
    {
      "eventID": 798350,
      "eventDateID": 14421,
      "EventDate": "2015-04-23T00:00:00",
      "StartTime": "7:00 PM",
      "EndTime": "8:00 PM",
      "Title": "All We Want Is LOVE: Liberation Of Victims Everywhere",
      "Description": "Ashley Harkrader is a co-founder of the non-profit All We Want Is LOVE, a non-profit organization that \"aims to fight the injustice of modern day slavery through education and liberation.\" She will speak to the students about the problem of sex trafficking, and about her experience as a survivor of sexual exploitation. Donations to LOVE146 will be accepted.",
      "PriceDescription": "N/A",
      "IsGLI": false,
      "Location": "Dina's Place",
      "Building": "DiGiorgio Campus Center",
      "ContactPersonName": "Sara Tennant",
      "ContactPersonPhoneNumber": "803/389-4266"
    },
    {
      "eventID": 797418,
      "eventDateID": 12708,
      "EventDate": "2015-04-23T00:00:00",
      "StartTime": "7:30 PM",
      "EndTime": "8:30 PM",
      "Title": "Ensemble Series: Winthrop Symphonic Band/Winthrop Wind Symphony",
      "Description": "student ensemble performance",
      "PriceDescription": "N/A",
      "IsGLI": false,
      "Location": "Byrnes Auditorium",
      "Building": "Byrnes Auditorium",
      "ContactPersonName": "Donna Guerra",
      "ContactPersonPhoneNumber": "323-2255"
    },
    {
      "eventID": 798422,
      "eventDateID": 14517,
      "EventDate": "2015-04-24T00:00:00",
      "StartTime": "2:30 PM",
      "EndTime": "4:15 PM",
      "Title": "Showcase of Undergraduate Research and Creative Endeavors (SOURCE) Performances",
      "Description": "Music, theatre and dance students perform their creative work as part of the Showcase",
      "PriceDescription": "N/A",
      "IsGLI": false,
      "Location": "Recital Hall",
      "Building": "Barnes Recital Hall",
      "ContactPersonName": "Robin Lammi",
      "ContactPersonPhoneNumber": ""
    },
    {
      "eventID": 798247,
      "eventDateID": 14297,
      "EventDate": "2015-04-25T00:00:00",
      "StartTime": "7:30 PM",
      "EndTime": "8:30 PM",
      "Title": "Ensemble Series: NLOLAIR Irish Ensemble",
      "Description": "Ensemble performance.",
      "PriceDescription": "N/A",
      "IsGLI": false,
      "Location": "Barnes Recital Hall",
      "Building": "Barnes Recital Hall",
      "ContactPersonName": "Donna Guerra",
      "ContactPersonPhoneNumber": "323-2255"
    },
    {
      "eventID": 798366,
      "eventDateID": 14442,
      "EventDate": "2015-04-26T00:00:00",
      "StartTime": "4:00 PM",
      "EndTime": "5:00 PM",
      "Title": "Special Event: Stephenie Stein, soprano and Daniel Stein, tenor",
      "Description": "Stephenie Stein, soprano and Daniel Stein, tenor will be presenting a recital that will include both classical and musical theatre music. Selections will include music from Elijah, La Bohème, Dogfight, The Last Five Years, and many more.",
      "PriceDescription": "N/A",
      "IsGLI": false,
      "Location": "Barnes Recital Hall",
      "Building": "Barnes Recital Hall",
      "ContactPersonName": "Donna Guerra",
      "ContactPersonPhoneNumber": "323-2255"
    },
    {
      "eventID": 797948,
      "eventDateID": 13874,
      "EventDate": "2015-04-27T00:00:00",
      "StartTime": "7:30 PM",
      "EndTime": "8:30 PM",
      "Title": "Ensemble Series: Winthrop Carolina/Wind Orchestra",
      "Description": "Ensemble performance.",
      "PriceDescription": "N/A",
      "IsGLI": false,
      "Location": "Byrnes Auditorium",
      "Building": "Byrnes Auditorium",
      "ContactPersonName": "Donna Guerra",
      "ContactPersonPhoneNumber": "323-2255"
    }
  ]
}